### ISSUE TITLE
[Q] Did you find a solution?

### ISSUE THREAD

**Issue by huuff** [ppfeiler/vite-openapi-bug#1]
I came across this repo on vitejs/vite#7226. I'm exactly on the same position as yours (my project config closely resembles this one). I found out that importing types as `import type` instead of plain `import` solves it... but obviously manually editing generated code is not a good solution. Did you find a better one?

**Comment by ppfeiler** [comment]
hi! We now use npm workspaces for that. 

So the openapi generator generates the client as a lib and we include it in our project. 

I try to create an branch here which shows our solution.

**Comment by huuff** [comment]
Thanks!

For the record, my (hacky) solution was to edit the generated files in the same script that generates the model:
```bash
sed -i 's|RequestArgs,||' "$GENERATED_DIR/api.ts"
sed -i "/from '\.\/base'/a import type \{ RequestArgs \} from '\.\/base';" "$GENERATED_DIR/api.ts"
sed -i 's|, RequestArgs||' "$GENERATED_DIR/common.ts"
sed -i "/from \"\.\/base\"/a import type \{ RequestArgs \} from '\.\/base';" "$GENERATED_DIR/common.ts"
```

But of course, your solution seems more elegant, so I'll give it a try.
